version: "3.0"

networks:
  cameratraps:
    driver: bridge

services:
  # the name `engine` is important here; in general, the sevice name is addressable by other conatiners on the same
  # docker network. The default "hostname" used by the python plugin library (pyevents) is "engine"
  engine:
    container_name: engine
    image: tapis/camera_traps_engine:0.4.0
    networks:
      - cameratraps
    environment:
      - TRAPS_CONFIG_FILE=/traps.toml
    volumes:
      # mount the traps.toml in the current working directory.
      - ../../installer/templates/config/traps.toml:/traps.toml:ro
      # mount the log4rs configuration file over the baked into the image.  Comment out
      # this mount if you want to use the image's default logging configuration.
      - ../../installer/templates/config/log4rs.yml:/resources/log4rs.yml

  imageDetecting:
    container_name: image_detecting
    image: tapis/image_detecting_plugin
    networks:
      - cameratraps
    pid: host
    privileged: true 
    volumes:
      - ./image_data:/var/lib/motion
    depends_on:
      - engine