# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gen_events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BoundingBox(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BoundingBox()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBoundingBox(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BoundingBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoundingBox
    def XCenter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BoundingBox
    def YCenter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BoundingBox
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BoundingBox
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BoundingBoxStart(builder): builder.StartObject(4)
def Start(builder):
    return BoundingBoxStart(builder)
def BoundingBoxAddXCenter(builder, xCenter): builder.PrependFloat32Slot(0, xCenter, 0.0)
def AddXCenter(builder, xCenter):
    return BoundingBoxAddXCenter(builder, xCenter)
def BoundingBoxAddYCenter(builder, yCenter): builder.PrependFloat32Slot(1, yCenter, 0.0)
def AddYCenter(builder, yCenter):
    return BoundingBoxAddYCenter(builder, yCenter)
def BoundingBoxAddWidth(builder, width): builder.PrependFloat32Slot(2, width, 0.0)
def AddWidth(builder, width):
    return BoundingBoxAddWidth(builder, width)
def BoundingBoxAddHeight(builder, height): builder.PrependFloat32Slot(3, height, 0.0)
def AddHeight(builder, height):
    return BoundingBoxAddHeight(builder, height)
def BoundingBoxEnd(builder): return builder.EndObject()
def End(builder):
    return BoundingBoxEnd(builder)