# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gen_events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImageLabelScore(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImageLabelScore()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImageLabelScore(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImageLabelScore
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImageLabelScore
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImageLabelScore
    def Probability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ImageLabelScoreStart(builder): builder.StartObject(2)
def Start(builder):
    return ImageLabelScoreStart(builder)
def ImageLabelScoreAddLabel(builder, label): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)
def AddLabel(builder, label):
    return ImageLabelScoreAddLabel(builder, label)
def ImageLabelScoreAddProbability(builder, probability): builder.PrependFloat32Slot(1, probability, 0.0)
def AddProbability(builder, probability):
    return ImageLabelScoreAddProbability(builder, probability)
def ImageLabelScoreEnd(builder): return builder.EndObject()
def End(builder):
    return ImageLabelScoreEnd(builder)