import os
import zmq
import logging
import json
import sys
import time
import toml
from pyevents.events import get_plugin_socket, get_next_msg, send_quit_command
from ctevents.ctevents import socket_message_to_typed_event, send_terminate_plugin_fb_event
from ctevents import ImageStoredEvent, ImageDeletedEvent, ImageScoredEvent, PluginTerminatingEvent, PluginTerminateEvent
from filelock import FileLock

log_level = os.environ.get("DETECTION_REPORTER_LOG_LEVEL", "INFO")
logger = logging.getLogger("Detection Reporter")
if log_level == "DEBUG":
    logger.setLevel(logging.DEBUG)
elif log_level == "INFO":
    logger.setLevel(logging.INFO)
elif log_level == "WARN":
    logger.setLevel(logging.WARN)
elif log_level == "ERROR":
    logger.setLevel(logging.ERROR)
if not logger.handlers:
    formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]')
    handler = logging.StreamHandler()
    handler.setFormatter(formatter)
    logger.addHandler(handler)

# Number of images generated by the entire application (i.e., by the image generating plugin)
total_images_generated = 0

# Number of images processed by this oracle plugin 
total_images_processed = 0

# Whether this program has received the PLuginTerminating event from the image generating plugin
received_terminating_signal = False

uuids_with_errors = []

PORT = int(os.environ.get('DETECTION_REPORTER_PLUGIN_PORT', 6012))
OUTPUT_DIR = os.environ.get('TRAPS_DETECTION_REPORTER_OUTPUT_PATH', "/output/")
DETECTION_FILE = os.environ.get('TRAPS_DETECTION_FILE', '/traps-detection.toml')

output_file = os.path.join(OUTPUT_DIR, "detections.csv")

SOCKET_TIMEOUT = 2000

def get_detection_thresholds():
    with open(DETECTION_FILE, 'r') as f:
        thresholds = toml.load(f)
    return thresholds

def get_socket():
    context = zmq.Context()
    return get_plugin_socket(context, PORT)  

def update_csv(cat, uuid, **kwargs):
    """
    This function updates the detections csv file.
    """
    if cat == 'DETECTION':
        model_result = kwargs.get('model_result')
        line = f'{cat}, {uuid}, {model_result}\n'
    elif cat == 'STORING':
        image_path = kwargs.get('image_path')
        decision = kwargs.get('decision')
        line = f'{cat}, {uuid}, {image_path}, {decision}\n'
    lock = FileLock(f'{output_file}.lock')
    try:
        with open(output_file, 'a') as f:
            f.write(line)
    except FileNotFoundError:
        # for the first image, the file has not been created yet and FileNotFound is expected
        if not total_images_processed == 0:
            logger.error(f"File not found: {output_file}")

def main():
    done = False
    detection_threshold = get_detection_thresholds()
    while not done:
        socket = get_socket()
        try:
            message = get_next_msg(socket)
        except zmq.error.Again:
            logger.debug(f"Got a zmq.error.Again; i.e., waited {SOCKET_TIMEOUT} ms without getting a message")
            continue
        except Exception as e:
            logger.debug(f"Got exception from get_next_msg; type(e): {type(e)}; e: {e}")
            done = True 
            logger.info("Oracle monitoring plugin stopping due to timeout limit...")
            continue
        if not message:
            logger.info("No message found in get_next_msg")

        logger.info("Got a message from the event socket - Detection reporter")
        event = socket_message_to_typed_event(message)

        if isinstance(event, ImageScoredEvent):
            uuid = event.ImageUuid().decode('utf-8')
            scores = [] # event.ScoresLength()
            detected = False
            for i in range(event.ScoresLength()):
                label = event.Scores(i).Label().decode('utf-8')
                prob = event.Scores(i).Probability()
                if label in detection_threshold and prob > detection_threshold[label]:
                    detected = True
                scores.append({"label": label, "probability": prob})
            timestamp = event.EventCreateTs().decode('utf-8')
            logger.info(f"Inside scoring {uuid} {scores} {timestamp}")
            update_csv('DETECTION', uuid, model_result=scores)

        elif isinstance(event, ImageStoredEvent):
            uuid = event.ImageUuid().decode('utf-8')
            #timestamp = event.EventCreateTs().decode('utf-8')
            destination = event.Destination().decode('utf-8')
            image_path = None
            logger.info(f"Image stored {uuid} {timestamp} {destination}")
            #update_csv('STORING', uuid, {"image_store_delete_time": timestamp, "image_decision": destination})
            update_csv('STORING', uuid, image_path=image_path, decision=destination)

        if isinstance(event, PluginTerminateEvent):
            logger.info(f"Received Terminate event * and shutting down image scoring plugin")
            send_quit_command(socket)
            sys.exit()

        #elif isinstance(event, PluginTerminatingEvent):
        #    plugin_name = event.PluginName().decode('utf-8')
        #    if plugin_name == 'ext_image_gen_plugin':
        #        logger.info("Received Terminating signal from image generating plugin")
        #        # at this point, we can compute the total images generated and to be processed from the
        #        # length of the uuid_image_mapping
        #        global received_terminating_signal
        #        received_terminating_signal = True
        #        total_images_generated = compute_total_images_generated()
        #        logger.info(f"Total images processed: {total_images_generated}")

        ## Once we have received the terminating signal, we compute total_images_processed 
        #if received_terminating_signal:
        #    total_images_processed = compute_total_images_processed()
        #    logger.info(f"Detection reporter has processed: {total_images_processed} out of {total_images_generated}")
        #    if total_images_generated < 0:
        #        total_images_generated = compute_total_images_generated()
       
        #if received_terminating_signal \
        #and total_images_generated > 0 \
        #and total_images_generated == total_images_processed:
        #    logger.info("Initiating shut down for all other plugins...")
        #    add_terminating_function_json("dfdcd2aa-1906-4153-bffb-45d85bc9a9ea")
        #    send_terminate_plugin_fb_event(socket, "*", "dfdcd2aa-1906-4153-bffb-45d85bc9a9ea")
        #    logger.info("Sent PluginTerminate * event")
        #    time.sleep(1)
        #    send_quit_command(socket)
        #    logger.info("Sent quit command.")
        #    sys.exit()
        #    #Leaving the uuid empty/* throws an error[Unable to parse string 'target_plugin_uuid' into a Uuid: invalid character: expected an optional prefix of `urn:uuid:`]
        #    #send_terminating_plugin_fb_event(socket,"ext_oracle_monitor_plugin","6e153711-9823-4ee6-b608-58e2e801db51")
        #else:
        #    logger.info(event)
        
if __name__ == '__main__':
    logger.info("Detection reporter plugin starting...")
    main()
    logger.info("Detection reporter plugin exiting...")
