# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gen_events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MonitorPowerStopEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MonitorPowerStopEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMonitorPowerStopEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MonitorPowerStopEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MonitorPowerStopEvent
    def EventCreateTs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MonitorPowerStopEvent
    def Pids(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MonitorPowerStopEvent
    def PidsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MonitorPowerStopEvent
    def PidsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MonitorPowerStopEvent
    def PidsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def MonitorPowerStopEventStart(builder): builder.StartObject(2)
def Start(builder):
    return MonitorPowerStopEventStart(builder)
def MonitorPowerStopEventAddEventCreateTs(builder, eventCreateTs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventCreateTs), 0)
def AddEventCreateTs(builder, eventCreateTs):
    return MonitorPowerStopEventAddEventCreateTs(builder, eventCreateTs)
def MonitorPowerStopEventAddPids(builder, pids): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pids), 0)
def AddPids(builder, pids):
    return MonitorPowerStopEventAddPids(builder, pids)
def MonitorPowerStopEventStartPidsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPidsVector(builder, numElems):
    return MonitorPowerStopEventStartPidsVector(builder, numElems)
def MonitorPowerStopEventEnd(builder): return builder.EndObject()
def End(builder):
    return MonitorPowerStopEventEnd(builder)