# Image: tapis/camera_traps_py:3.8
FROM tapis/pyevents:3.8

ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

ADD labrador-pup.jpg /labrador-pup.jpg
ADD gen_events /gen_events
ADD ctevents.py /ctevents.py
