# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gen_events

class EventType(object):
    NONE = 0
    NewImageEvent = 1
    ImageReceivedEvent = 2
    ImageScoredEvent = 3
    ImageStoredEvent = 4
    ImageDeletedEvent = 5
    PluginStartedEvent = 6
    PluginTerminatingEvent = 7
    PluginTerminateEvent = 8
    MonitorPowerStartEvent = 9
    MonitorPowerStopEvent = 10
