# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gen_events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PluginStartedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PluginStartedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPluginStartedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PluginStartedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PluginStartedEvent
    def EventCreateTs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginStartedEvent
    def PluginName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginStartedEvent
    def PluginUuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PluginStartedEventStart(builder): builder.StartObject(3)
def Start(builder):
    return PluginStartedEventStart(builder)
def PluginStartedEventAddEventCreateTs(builder, eventCreateTs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventCreateTs), 0)
def AddEventCreateTs(builder, eventCreateTs):
    return PluginStartedEventAddEventCreateTs(builder, eventCreateTs)
def PluginStartedEventAddPluginName(builder, pluginName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pluginName), 0)
def AddPluginName(builder, pluginName):
    return PluginStartedEventAddPluginName(builder, pluginName)
def PluginStartedEventAddPluginUuid(builder, pluginUuid): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pluginUuid), 0)
def AddPluginUuid(builder, pluginUuid):
    return PluginStartedEventAddPluginUuid(builder, pluginUuid)
def PluginStartedEventEnd(builder): return builder.EndObject()
def End(builder):
    return PluginStartedEventEnd(builder)