import os
import zmq
import logging
import json
import sys
import time
from pyevents.events import get_plugin_socket, get_next_msg, send_quit_command
from ctevents.ctevents import socket_message_to_typed_event, send_terminate_plugin_fb_event
from ctevents import ImageStoredEvent, ImageDeletedEvent, ImageScoredEvent, ImageReceivedEvent, PluginTerminatingEvent

# Try to import Kafka producer, handle gracefully if not available
try:
    from confluent_kafka import Producer, KafkaError
    from confluent_kafka.admin import AdminClient
    KAFKA_AVAILABLE = True
except ImportError:
    KAFKA_AVAILABLE = False
    logger = logging.getLogger("CKN Plugin")
    logger.warning("confluent-kafka not available. Kafka streaming will be disabled.")

# Try to import power processor, handle gracefully if not available
try:
    from power_processor import PowerProcessor
    POWER_PROCESSOR_AVAILABLE = True
except ImportError:
    POWER_PROCESSOR_AVAILABLE = False

log_level = os.environ.get("CKN_LOG_LEVEL", "INFO")
logger = logging.getLogger("CKN Plugin")
if log_level == "DEBUG":
    logger.setLevel(logging.DEBUG)
elif log_level == "INFO":
    logger.setLevel(logging.INFO)
elif log_level == "WARN":
    logger.setLevel(logging.WARN)
elif log_level == "ERROR":
    logger.setLevel(logging.ERROR)
if not logger.handlers:
    formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]')
    handler = logging.StreamHandler()
    handler.setFormatter(formatter)
    logger.addHandler(handler)

# Number of images generated by the entire application (i.e., by the image generating plugin)
total_images_generated = 0

# Number of images processed by this CKN plugin 
total_images_processed = 0

# Whether this program has received the PluginTerminating event from the image generating plugin
received_terminating_signal = False

# list of image UUIDs for which the CKN plugin is not able to initially retrieve the basic information 
# from the uuid_image_mapping file (written by image generating plugin)
uuids_with_errors = []

# Set of UUIDs that have been sent to Kafka to avoid duplicates
processed_uuids = set()

# Kafka producer instance
kafka_producer = None

PORT = int(os.environ.get('CKN_PLUGIN_PORT', 6011))
OUTPUT_DIR = os.environ.get('TRAPS_CKN_OUTPUT_PATH', "/output/")
MODEL_ID = os.environ.get("MODEL_ID")

# Kafka configuration
KAFKA_BROKER = os.environ.get('CKN_KAFKA_BROKER', 'localhost:9092')
KAFKA_TOPIC = os.environ.get('CKN_KAFKA_TOPIC', 'oracle-events')
DEVICE_ID = os.environ.get('CAMERA_TRAPS_DEVICE_ID', '')
EXPERIMENT_ID = os.environ.get('EXPERIMENT_ID', '')
USER_ID = os.environ.get('USER_ID', '')

# Power monitoring configuration
ENABLE_POWER_MONITORING = os.environ.get('ENABLE_POWER_MONITORING', 'false')
POWER_SUMMARY_FILE = os.environ.get('POWER_SUMMARY_FILE', '')
POWER_SUMMARY_TOPIC = os.environ.get('POWER_SUMMARY_TOPIC', 'cameratraps-power-summary')

# This is the ground truth file; this file is written by the image generating plugin and only read
# by the CKN plugin (not written to)
uuid_image_mapping_path = os.path.join(OUTPUT_DIR, "uuid_image_mapping.json")

# Image detecting plugin
VIDEO_INFO_FILE = os.environ.get('VIDEO_INFO_FILE', '')

# This is the file the CKN plugin actually writes
output_file = os.path.join(OUTPUT_DIR, "image_mapping_final.json")

SOCKET_TIMEOUT = 2000


def get_socket():
    context = zmq.Context()
    return get_plugin_socket(context, PORT)


def test_ckn_broker_connection(configuration, timeout=10, num_tries=5):
    """
    Checks if the CKN broker is up and running.
    """
    if not KAFKA_AVAILABLE:
        return False
    for i in range(num_tries):
        try:
            admin_client = AdminClient(configuration)
            # Access the topics, if not successful wait
            topics = admin_client.list_topics(timeout=timeout)
            return True
        except Exception as e:
            logger.info(f"CKN broker not available yet: {e}. Retrying in 5 seconds...")
            time.sleep(5)
    logger.info(f"Could not connect to the CKN broker...")
    return False


def initialize_kafka_producer():
    """
    Initialize Kafka producer with SSL configuration.
    """
    global kafka_producer
    if not KAFKA_AVAILABLE:
        logger.warning("Kafka not available, skipping producer initialization")
        return False
    
    kafka_conf = {'bootstrap.servers': KAFKA_BROKER, 'log_level': 0, 'security.protocol': 'SSL'}
    
    logger.info(f"Connecting to the CKN broker at {KAFKA_BROKER}")
    
    # Wait for CKN broker to be available
    ckn_broker_available = test_ckn_broker_connection(kafka_conf)
    
    if not ckn_broker_available:
        logger.warning(f"Shutting down CKN Plugin Kafka producer due to broker not being available")
        return False
    
    # Successful connection to CKN broker
    logger.info(f"Successfully connected to the CKN broker at {KAFKA_BROKER}")
    
    # Initialize the Kafka producer
    kafka_producer = Producer(**kafka_conf)
    return True


def stream_event_to_kafka(event_data):
    """
    Stream event to Kafka broker.
    """
    global kafka_producer, processed_uuids
    
    if not kafka_producer:
        return
    
    uuid = event_data.get('UUID')
    if not uuid or uuid in processed_uuids:
        return
    
    try:
        # Add metadata to event
        event_data['device_id'] = DEVICE_ID
        event_data['experiment_id'] = EXPERIMENT_ID
        event_data['user_id'] = USER_ID
        
        row_json = json.dumps(event_data)
        
        # Send the event
        kafka_producer.produce(KAFKA_TOPIC, key=EXPERIMENT_ID, value=row_json)
        kafka_producer.flush()
        
        # Add to processed set only if produce succeeds
        processed_uuids.add(uuid)
        logger.info(f"Streamed event to Kafka for UUID: {uuid}")
        
    except BufferError as e:
        logger.error(f"Buffer error streaming to Kafka: {e}")
    except Exception as e:
        logger.error(f"Kafka error streaming event: {e}")


def compute_total_images_generated():
    """
    Reads the uuid_image_mapping file to determine how many images were generated by this execution.
    """
    if os.path.exists(uuid_image_mapping_path):
        with open(uuid_image_mapping_path, 'r') as f:
            try:
                d = json.load(f)
            except Exception as e:
                logger.error(f"Error parsing uuid_image_mapping file when trying to compute total images generated; details: {e}")
                return -1 
        # the number of images generated is just the total number of keys in the file
        return len(d.keys())
    elif os.path.exists(VIDEO_INFO_FILE):
        with open(VIDEO_INFO_FILE, 'r') as f:
            video_info = yaml.safe_load(f)
            return video_info.get('num_images')
    else:
        logger.error(f"Error parsing uuid_image_mapping file when trying to compute total images generated; details: {e}")
        return -1 


def compute_total_images_processed():
    """
    Reads the image_mapping_final file to determine how many images have been processed.
    """
    total = 0
    with open(output_file, 'r') as f:
        try:
            d = json.load(f)
        except Exception as e:
            logger.error(f"Error parsing image_mapping_final file when trying to compute total images processed; details: {e}")
            return total
    # read through the entries and count all images which have a final decision
    for _, v in d.items():
        if v.get("image_decision"):
            total += 1
    return total


def update_json(uuid, updated_data):
    """
    This function updates the existing image_mapping_final dictionary for a given image with id, `uuid`, 
    and a dictionary, `updated_data`, with additional fields to write for the image. 
    """
    global total_images_processed, total_images_generated
    
    # load current dictionary from the image_mapping_final file 
    existing_image_mapping_final = {}
    try:
        with open(output_file, 'r') as f:
            try:
                existing_image_mapping_final = json.load(f)
            except json.JSONDecodeError as e:
                logger.error(f"JSON decoding error for {output_file}; details: {e}")        
    except FileNotFoundError:
        # for the first image, the file has not been created yet and FileNotFound is expected
        if not total_images_processed == 0:
            logger.error(f"File not found: {output_file}")

    # if the uuid is not yet in the image_mapping_final file, go to the uuid_image_mapping file, written
    # by the image generating plugin, to get basic information. The uuid should always be in this file 
    # since the image generating plugin writes the uuid to that file before sending a new image event, 
    if uuid not in existing_image_mapping_final:
        logger.info(f"Fetching {uuid} from {uuid_image_mapping_path}")
        uuid_image_mapping = {}
        try:
            with open(uuid_image_mapping_path, 'r') as file:
                try:
                    uuid_image_mapping = json.load(file)
                    # If we were able to load the uuid_image_mapping file, try to recover any UUID that 
                    # was previously on the error list 
                    if uuids_with_errors:
                        for failed_uuid in uuids_with_errors:
                            if failed_uuid in existing_image_mapping_final:
                                existing_image_mapping_final[failed_uuid].update(uuid_image_mapping[failed_uuid])
                            else:
                               existing_image_mapping_final[failed_uuid] = uuid_image_mapping[failed_uuid]
                            uuids_with_errors.remove(failed_uuid)
                
                # it is possible the image generating plugin was writing to the file at the same time and,
                # at the moment we read the file, the contents of the file are not valid JSON.
                except json.JSONDecodeError as e:                    
                    logger.error(f"JSON loading Error loading uuid_image_mapping.json file while processing uuid: {uuid}; details: {e}")
                    # we were not able to read the uuid_image_mapping.json file, so add this uuid to the error list
                    uuids_with_errors.append(uuid)
        except FileNotFoundError:
            # the uuid_image_mapping file should always at least exist
            logger.error(f"File {uuid_image_mapping_path} not found. This is unexpected and represents a bug.")

        # use the uuid_image_mapping file to get the base info for this image, if possible, and otherwise,
        # create a new dictionary with just the UUID field.
        existing_image_mapping_final[uuid] = uuid_image_mapping.get(uuid, {"UUID": uuid})

    # iterate through the update_data parameter and add them to the existing data
    for key, value in updated_data.items():
        existing_image_mapping_final[uuid][key] = value    
    
    # write the updates mapping back to the file
    with open(output_file, "w") as f: 
        json.dump(existing_image_mapping_final, f, indent=2)
    
    # If image_decision is present, stream to Kafka
    if "image_decision" in updated_data:
        # Read the complete entry to stream
        event_entry = existing_image_mapping_final.get(uuid, {})
        if event_entry:
            # Build event payload from the JSON entry
            event_payload = build_event_payload(event_entry)
            if event_payload:
                stream_event_to_kafka(event_payload)


def build_event_payload(event_entry):
    """
    Build event payload from JSON entry for Kafka streaming.
    No metrics computation - just forward raw data.
    """
    uuid = event_entry.get("UUID")
    if not uuid:
        return None
    
    # Extract all relevant fields
    image_count = event_entry.get("image_count")
    image_name = event_entry.get("image_name")
    ground_truth = event_entry.get("ground_truth")
    ground_truth_boxes = event_entry.get("ground_truth_boxes") or event_entry.get("ground_truth_bboxes")
    image_receiving_timestamp = event_entry.get("image_receiving_timestamp")
    image_scoring_timestamp = event_entry.get("image_scoring_timestamp")
    image_store_delete_time = event_entry.get("image_store_delete_time") or event_entry.get("image_delete_time")
    image_decision = event_entry.get("image_decision")
    model_id = event_entry.get("model_id") or MODEL_ID
    
    # Extract scores
    scores = event_entry.get("score", [])
    flattened_scores = json.dumps(scores) if scores else None
    
    # Extract highest probability label and probability
    label = None
    probability = 0.0
    if scores:
        highest_score = max(scores, key=lambda x: x.get("probability", 0.0))
        label = highest_score.get("label")
        probability = highest_score.get("probability", 0.0)
    
    # Build event payload
    event = {
        "image_count": image_count,
        "UUID": uuid,
        "image_name": image_name,
        "ground_truth": ground_truth,
        "image_receiving_timestamp": image_receiving_timestamp,
        "image_scoring_timestamp": image_scoring_timestamp,
        "model_id": model_id,
        "label": label,
        "probability": probability,
        "image_store_delete_time": image_store_delete_time,
        "image_decision": image_decision,
        "flattened_scores": flattened_scores,
    }
    
    # Add ground truth boxes if available
    if ground_truth_boxes:
        event["ground_truth_boxes"] = ground_truth_boxes
    
    return event


def add_terminating_function_json(special_uuid):
    """
    This function writes a 'special' UUID that may be used for compatibility.
    It first checks one last time for images in the uuids_with_errors file and tries to retrieve 
    them 
    """
    # read the existing output data 
    with open(output_file, "r") as f: 
        existing_image_mapping_final = json.load(f)
    
    # check if we still have UUIDs with errors
    if uuids_with_errors:
        uuid_image_mapping = {}
        # try to read the mapping file and make the corrections
        try:
            with open(uuid_image_mapping_path, 'r') as file:
                try:
                    uuid_image_mapping = json.load(file)
                except Exception as e:
                    logger.error(f"Could not load JSON from uuid_image_mapping file at the very end; details: {e}")
        except Exception as e:
            logger.error(f"Got exception trying to open the uuid_image_mapping file at the very end; details: {e}")
        if uuid_image_mapping:
            for failed_uuid in uuids_with_errors:
                # we should always have SOME data for all failed uuids, so this 
                if not existing_image_mapping_final.get(failed_uuid):
                    existing_image_mapping_final[failed_uuid] = {}
                    logger.error(f"In final processing and existing_image_mapping_final had no data for uuid {failed_uuid}")
                # extend the existing mapping data with the uuid data
                existing_image_mapping_final[failed_uuid].update(uuid_image_mapping[failed_uuid])
                uuids_with_errors.remove(failed_uuid)
                logger.info(f"Updated final mapping at the end for failed UUID {failed_uuid}")

    # add the special UUID to the mapping file; it gets an empty dict since it does not correspond to a 
    # real image
    existing_image_mapping_final[special_uuid] = {}
    
    # write the complete mapping file:
    with open(output_file, "w") as f: 
        json.dump(existing_image_mapping_final, f, indent=2)


def process_power_summary():
    """
    Process power summary at shutdown if enabled.
    """
    if ENABLE_POWER_MONITORING.lower() != 'false' and POWER_PROCESSOR_AVAILABLE and POWER_SUMMARY_FILE:
        try:
            power_processor = PowerProcessor(
                POWER_SUMMARY_FILE, 
                kafka_producer, 
                POWER_SUMMARY_TOPIC, 
                EXPERIMENT_ID, 
                5,  # max_tries
                10  # timeout
            )
            power_processor.process_summary_events()
            logger.info("Power summary processed.")
        except Exception as e:
            logger.warning(f"Could not process power summary: {e}")
    elif ENABLE_POWER_MONITORING.lower() != 'false':
        logger.warning("Power monitoring enabled but power_processor module not available or POWER_SUMMARY_FILE not set")


def main():
    """
    Main loop for CKN plugin; this function waits for new messages on the event socket and processes accordingly:
      1. Image received, scored, stored, deleted: update the image_mapping_final and stream to Kafka
      2. Plugin terminating (from image generating): Compute total images needed to be processed.
    """
    # Initialize Kafka producer
    initialize_kafka_producer()
    
    done = False
    while not done:
        socket = get_socket()
        try:
            message = get_next_msg(socket)
        except zmq.error.Again:
            logger.debug(f"Got a zmq.error.Again; i.e., waited {SOCKET_TIMEOUT} ms without getting a message")
            continue
        except Exception as e:
            logger.debug(f"Got exception from get_next_msg; type(e): {type(e)}; e: {e}")
            done = True 
            logger.info("CKN plugin stopping due to timeout limit...")
            continue
        if not message:
            logger.info("No message found in get_next_msg")

        logger.info("Got a message from the event socket - CKN plugin check")
        event = socket_message_to_typed_event(message)

        if isinstance(event, ImageReceivedEvent):
            uuid = event.ImageUuid().decode('utf-8')
            timestamp = event.EventCreateTs().decode('utf-8').strip("'")
            logger.info(f"Image received {uuid} {timestamp}")
            update_json(uuid, {"image_receiving_timestamp": timestamp})

        elif isinstance(event, ImageScoredEvent):
            uuid = event.ImageUuid().decode('utf-8')
            scores = []
            for i in range(event.ScoresLength()):
                label = event.Scores(i).Label().decode('utf-8')
                prob = event.Scores(i).Probability()
                scores.append({"label": label, "probability": prob})
            timestamp = event.EventCreateTs().decode('utf-8')
            logger.info(f"Inside scoring {uuid} {scores} {timestamp}")
            update_json(uuid, {"image_scoring_timestamp": timestamp, "score": scores})

        elif isinstance(event, ImageStoredEvent):
            uuid = event.ImageUuid().decode('utf-8')
            timestamp = event.EventCreateTs().decode('utf-8')
            destination = event.Destination().decode('utf-8')
            logger.info(f"Image stored {uuid} {timestamp} {destination}")
            update_json(uuid, {"image_store_delete_time": timestamp, "image_decision": destination})

        elif isinstance(event, ImageDeletedEvent):
            uuid = event.ImageUuid().decode('utf-8')
            timestamp = event.EventCreateTs().decode('utf-8')
            logger.info(f"Image deleted {uuid} {timestamp}")
            update_json(uuid, {"image_delete_time": timestamp, "image_decision": "Deleted"})

        elif isinstance(event, PluginTerminatingEvent):
            plugin_name = event.PluginName().decode('utf-8')
            if plugin_name == 'ext_image_gen_plugin':
                logger.info("Received Terminating signal from image generating plugin")
                # at this point, we can compute the total images generated and to be processed from the
                # length of the uuid_image_mapping
                global received_terminating_signal
                received_terminating_signal = True
                total_images_generated = compute_total_images_generated()
                logger.info(f"Total images generated: {total_images_generated}")         
        
        # Once we have received the terminating signal, we compute total_images_processed 
        if received_terminating_signal:
            total_images_processed = compute_total_images_processed()
            logger.info(f"CKN plugin has processed: {total_images_processed} out of {total_images_generated}")       
            if total_images_generated < 0:
                total_images_generated = compute_total_images_generated()
       
        if received_terminating_signal \
        and total_images_generated > 0 \
        and total_images_generated == total_images_processed:
            logger.info("Initiating shut down for all other plugins...")
            add_terminating_function_json("6e153711-9823-4ee6-b608-58e2e801db51")
            send_terminate_plugin_fb_event(socket, "*", "6e153711-9823-4ee6-b608-58e2e801db51")
            logger.info("Sent PluginTerminate * event")
            time.sleep(1)
            
            # Process power summary if enabled
            process_power_summary()
            
            send_quit_command(socket)
            logger.info("Sent quit command.")
            sys.exit()
        else:
            logger.info(event)


if __name__ == '__main__':
    logger.info("CKN plugin starting...")
    main()
    logger.info("CKN plugin exiting...")

