"""
CKN Plugin - Combined Oracle and CKN Daemon functionality.

This plugin:
1. Listens on ZMQ for image events (ImageReceived, ImageScored, ImageStored, ImageDeleted, PluginTerminating)
2. Keeps mapping state in memory (no image_mapping_final.json)
3. Computes running experiment metrics (TP/FP/FN, precision, recall, f1, IoU, mAP)
4. Streams per-image events to Kafka when image_decision is set (when CKN is configured)
5. Streams power summary to Kafka at shutdown (when power monitoring is enabled)
"""

import os
import sys
import zmq
import logging
import json
import time

from pyevents.events import get_plugin_socket, get_next_msg, send_quit_command
from ctevents.ctevents import socket_message_to_typed_event, send_terminate_plugin_fb_event
from ctevents import ImageStoredEvent, ImageDeletedEvent, ImageScoredEvent, ImageReceivedEvent, PluginTerminatingEvent

# Try to import Kafka producer, handle gracefully if not available
KAFKA_AVAILABLE = False
try:
    from confluent_kafka import Producer, KafkaError
    from confluent_kafka.admin import AdminClient
    KAFKA_AVAILABLE = True
except ImportError:
    pass

# ============================================================================
# Logging setup
# ============================================================================
log_level = os.environ.get("CKN_LOG_LEVEL", "INFO")
LOG_FILE = os.environ.get("CKN_LOG_FILE", "/output/ckn_plugin.log")

logger = logging.getLogger("CKN Plugin")
if log_level == "DEBUG":
    logger.setLevel(logging.DEBUG)
elif log_level == "INFO":
    logger.setLevel(logging.INFO)
elif log_level == "WARN":
    logger.setLevel(logging.WARN)
elif log_level == "ERROR":
    logger.setLevel(logging.ERROR)

if not logger.handlers:
    formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]')
    
    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)
    
    # File handler
    try:
        log_dir = os.path.dirname(LOG_FILE)
        if log_dir and not os.path.exists(log_dir):
            os.makedirs(log_dir, exist_ok=True)
        file_handler = logging.FileHandler(LOG_FILE)
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
        logger.info(f"Logging to file: {LOG_FILE}")
    except Exception as e:
        logger.warning(f"Could not create log file {LOG_FILE}: {e}")

# ============================================================================
# Configuration from environment
# ============================================================================
PORT = int(os.environ.get('CKN_PLUGIN_PORT', 6011))
OUTPUT_DIR = os.environ.get('TRAPS_CKN_OUTPUT_PATH', "/output/")
MODEL_ID = os.environ.get("MODEL_ID")

# Ground truth file (written by image generating plugin, read-only for us)
uuid_image_mapping_path = os.path.join(OUTPUT_DIR, "uuid_image_mapping.json")

# Kafka configuration
KAFKA_BROKER = os.environ.get('CKN_KAFKA_BROKER', '')
KAFKA_TOPIC = os.environ.get('CKN_KAFKA_TOPIC', 'oracle-events')
KAFKA_SECURITY_PROTOCOL = os.environ.get('CKN_KAFKA_SECURITY_PROTOCOL', 'SSL')
DEVICE_ID = os.environ.get('CAMERA_TRAPS_DEVICE_ID', '')
CKN_DOMAIN = os.environ.get('CKN_DOMAIN', 'animal-ecology')
USER_ID = os.environ.get('USER_ID', '')
EXPERIMENT_ID = os.environ.get('EXPERIMENT_ID', '')

# Power monitoring configuration
ENABLE_POWER_MONITORING = os.environ.get('ENABLE_POWER_MONITORING', 'false').lower()
POWER_SUMMARY_FILE = os.environ.get('POWER_SUMMARY_FILE', '')
POWER_SUMMARY_TOPIC = os.environ.get('POWER_SUMMARY_TOPIC', 'cameratraps-power-summary')
POWER_SUMMARY_TIMEOUT = int(os.environ.get('POWER_SUMMARY_TIMEOUT', 10))
POWER_SUMMARY_MAX_TRIES = int(os.environ.get('POWER_SUMMARY_MAX_TRIES', 5))

# Special UUID used to signal experiment end
EXPERIMENT_END_SIGNAL = os.getenv('EXPERIMENT_END_SIGNAL', '6e153711-9823-4ee6-b608-58e2e801db51')

SOCKET_TIMEOUT = 2000

# ============================================================================
# Global state
# ============================================================================
# In-memory mapping (replaces image_mapping_final.json)
existing_image_mapping = {}

# Number of images generated by the entire application
total_images_generated = 0

# Number of images processed (have image_decision set)
total_images_processed = 0

# Whether we received the PluginTerminating event from image generating plugin
received_terminating_signal = False

# UUIDs we couldn't initially retrieve from uuid_image_mapping
uuids_with_errors = []

# Set of UUIDs already streamed to Kafka
processed_uuids = set()

# Kafka producer (initialized if KAFKA_BROKER is set)
kafka_producer = None

# Running experiment metrics
experiment_metrics = {
    "total_images": 0,
    "total_predictions": 0,
    "total_ground_truth_objects": 0,
    "true_positives": 0,
    "false_positives": 0,
    "false_negatives": 0,
    "precision": 0.0,
    "recall": 0.0,
    "f1_score": 0.0,
    "mean_iou": None,
    "map_50": None,
    "map_50_95": None,
    # Internal accumulators
    "sum_iou": 0.0,
    "num_iou_pairs": 0,
    "gt_boxes_count": 0,
}

# For mAP: per-threshold prediction lists of (score, is_tp)
map_thresholds = [round(t, 2) for t in [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]]
map_data = {t: [] for t in map_thresholds}


# ============================================================================
# Kafka Connect JSON schema envelopes
# ============================================================================
# The JDBC sink connectors on cknkafkaconnect run with
# value.converter.schemas.enable=true, so JsonConverter requires each record
# to be a {"schema": ..., "payload": ...} envelope rather than bare JSON.
EVENT_FIELD_TYPES = {
    "domain": "string",
    "device_id": "string",
    "experiment_id": "string",
    "user_id": "string",
    "model_id": "string",
    "image_count": "int32",
    "UUID": "string",
    "image_name": "string",
    "ground_truth": "string",
    "image_receiving_timestamp": "string",
    "image_scoring_timestamp": "string",
    "image_store_delete_time": "string",
    "label": "string",
    "probability": "double",
    "image_decision": "string",
    "flattened_scores": "string",
    "total_images": "int32",
    "total_predictions": "int32",
    "total_ground_truth_objects": "int32",
    "true_positives": "int32",
    "false_positives": "int32",
    "false_negatives": "int32",
    "precision": "double",
    "recall": "double",
    "f1_score": "double",
    "mean_iou": "double",
    "map_50": "double",
    "map_50_95": "double",
}
EVENT_REQUIRED_FIELDS = {"UUID", "experiment_id", "user_id"}


def build_connect_envelope(payload, field_types, required_fields=None):
    """Wrap a flat dict in a Kafka Connect JSON schema envelope (schema+payload)."""
    required_fields = required_fields or set()
    fields = [
        {"field": name, "type": conn_type, "optional": name not in required_fields}
        for name, conn_type in field_types.items()
    ]
    schema = {"type": "struct", "fields": fields, "optional": False}
    return {"schema": schema, "payload": payload}


def build_power_field_types(flattened_event):
    """Power summary keys are dynamic (per-plugin names), so infer types from the event."""
    return {
        name: "string" if name == "experiment_id" else "double"
        for name in flattened_event
    }


# ============================================================================
# Kafka helpers
# ============================================================================
def validate_broker_address(broker_address):
    """Validate the broker address format."""
    if not broker_address:
        return False, "Broker address is empty"
    
    # Check basic format (host:port)
    if ':' not in broker_address:
        return False, f"Invalid broker format '{broker_address}' - expected 'host:port'"
    
    parts = broker_address.rsplit(':', 1)
    host = parts[0]
    port_str = parts[1]
    
    # Validate port
    try:
        port = int(port_str)
        if port < 1 or port > 65535:
            return False, f"Invalid port {port} - must be between 1 and 65535"
    except ValueError:
        return False, f"Invalid port '{port_str}' - must be a number"
    
    # Validate host is not empty
    if not host:
        return False, "Host cannot be empty"
    
    return True, f"Broker address '{broker_address}' is valid (host={host}, port={port})"


def test_kafka_connection(configuration, timeout=10, num_tries=5):
    """Check if the Kafka broker is up and running."""
    if not KAFKA_AVAILABLE:
        logger.error("Kafka client library (confluent-kafka) not available")
        return False
    
    broker = configuration.get('bootstrap.servers', 'unknown')
    security_protocol = configuration.get('security.protocol', 'unknown')
    
    logger.info(f"Testing Kafka connection to {broker} with protocol {security_protocol}")
    
    for i in range(num_tries):
        try:
            logger.info(f"Connection attempt {i+1}/{num_tries}...")
            admin_client = AdminClient(configuration)
            topics = admin_client.list_topics(timeout=timeout)
            topic_list = list(topics.topics.keys())
            logger.info(f"Successfully connected! Available topics: {topic_list[:10]}{'...' if len(topic_list) > 10 else ''}")
            return True
        except Exception as e:
            error_msg = str(e)
            logger.warning(f"Kafka connection attempt {i+1}/{num_tries} failed: {error_msg}")
            if i < num_tries - 1:
                logger.info(f"Retrying in 5 seconds...")
                time.sleep(5)
    
    logger.error(f"Could not connect to Kafka broker after {num_tries} attempts")
    return False


def init_kafka_producer():
    """Initialize Kafka producer if configured."""
    global kafka_producer
    
    logger.info("="*60)
    logger.info("Initializing Kafka Producer")
    logger.info("="*60)
    
    # Check if Kafka library is available
    if not KAFKA_AVAILABLE:
        logger.error("Kafka client library (confluent-kafka) not installed. CKN streaming disabled.")
        return False
    
    # Check if broker is configured
    if not KAFKA_BROKER:
        logger.warning("CKN_KAFKA_BROKER environment variable not set. CKN streaming disabled.")
        return False
    
    # Validate broker address format
    is_valid, validation_msg = validate_broker_address(KAFKA_BROKER)
    logger.info(f"Broker validation: {validation_msg}")
    if not is_valid:
        logger.error(f"Invalid broker address: {validation_msg}")
        return False
    
    # Log configuration
    logger.info(f"Kafka Configuration:")
    logger.info(f"  - Broker: {KAFKA_BROKER}")
    logger.info(f"  - Security Protocol: {KAFKA_SECURITY_PROTOCOL}")
    logger.info(f"  - Topic: {KAFKA_TOPIC}")
    logger.info(f"  - Experiment ID: {EXPERIMENT_ID}")
    logger.info(f"  - User ID: {USER_ID}")
    logger.info(f"  - Device ID: {DEVICE_ID}")
    
    kafka_conf = {
        'bootstrap.servers': KAFKA_BROKER,
        'log_level': 0,
        'security.protocol': KAFKA_SECURITY_PROTOCOL
    }
    
    logger.info(f"Attempting to connect to Kafka broker at {KAFKA_BROKER}...")
    
    if not test_kafka_connection(kafka_conf):
        logger.error("Failed to connect to Kafka broker. CKN streaming disabled.")
        logger.info("="*60)
        return False
    
    logger.info(f"Successfully connected to Kafka broker!")
    kafka_producer = Producer(**kafka_conf)
    logger.info("Kafka producer initialized successfully")
    logger.info("="*60)
    return True


# ============================================================================
# Metrics computation (ported from oracle_ckn_daemon)
# ============================================================================
def _compute_iou(box_a, box_b):
    """Compute IoU between two boxes in [x, y, w, h] format with normalized coordinates."""
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b
    ax2, ay2 = ax + aw, ay + ah
    bx2, by2 = bx + bw, by + bh
    inter_x1 = max(ax, bx)
    inter_y1 = max(ay, by)
    inter_x2 = min(ax2, bx2)
    inter_y2 = min(ay2, by2)
    inter_w = max(0.0, inter_x2 - inter_x1)
    inter_h = max(0.0, inter_y2 - inter_y1)
    inter_area = inter_w * inter_h
    area_a = max(0.0, aw) * max(0.0, ah)
    area_b = max(0.0, bw) * max(0.0, bh)
    union = area_a + area_b - inter_area
    return (inter_area / union) if union > 0 else 0.0


def _greedy_match(preds, gts, iou_threshold):
    """
    Greedy 1-1 matching between predictions and ground truths by IoU threshold.
    Returns list of (pred_idx, gt_idx, iou) for matches.
    """
    matches = []
    used_preds = set()
    used_gts = set()
    # Precompute IoU matrix
    candidates = []
    for pi, p in enumerate(preds):
        pbox = p.get("bounding_box")
        if pbox is None:
            continue
        for gi, g in enumerate(gts):
            gbox = g.get("bounding_box")
            if gbox is None:
                continue
            iou = _compute_iou(pbox, gbox)
            candidates.append((iou, pi, gi))
    # Sort by descending IoU
    candidates.sort(reverse=True)
    for iou, pi, gi in candidates:
        if iou < iou_threshold:
            break
        if pi in used_preds or gi in used_gts:
            continue
        matches.append((pi, gi, iou))
        used_preds.add(pi)
        used_gts.add(gi)
    return matches, used_preds, used_gts


def _update_map_structures(predictions, gt_boxes):
    """Update per-threshold AP structures using label-aware matches."""
    global map_data
    for thr in map_thresholds:
        matches, used_preds, used_gts = _greedy_match(predictions, gt_boxes, thr)
        matched_gt_by_pred = {pi: gi for pi, gi, _ in matches}
        for pi, pred in enumerate(predictions):
            score = float(pred.get("probability", 0.0))
            if pi in matched_gt_by_pred:
                gi = matched_gt_by_pred[pi]
                if str(pred.get("label")) == str(gt_boxes[gi].get("label")):
                    map_data[thr].append((score, True))
                else:
                    map_data[thr].append((score, False))
            else:
                map_data[thr].append((score, False))


def _compute_ap(preds_list, num_gt):
    """
    Compute AP given list of (score, is_tp) and total GT count.
    Uses precision envelope integration.
    """
    if num_gt <= 0 or not preds_list:
        return 0.0
    preds_sorted = sorted(preds_list, key=lambda x: x[0], reverse=True)
    tp_cum = 0
    fp_cum = 0
    precisions = []
    recalls = []
    for score, is_tp in preds_sorted:
        if is_tp:
            tp_cum += 1
        else:
            fp_cum += 1
        precision = tp_cum / max(tp_cum + fp_cum, 1)
        recall = tp_cum / num_gt
        precisions.append(precision)
        recalls.append(recall)
    # Precision envelope
    for i in range(len(precisions) - 2, -1, -1):
        if precisions[i] < precisions[i + 1]:
            precisions[i] = precisions[i + 1]
    # Integrate AP
    ap = 0.0
    prev_recall = 0.0
    for p, r in zip(precisions, recalls):
        if r > prev_recall:
            ap += p * (r - prev_recall)
            prev_recall = r
    return ap


def _update_experiment_metrics(ground_truth_label, scores_list, ground_truth_boxes=None):
    """
    Update running experiment metrics based on a single image's ground truth label and predictions.
    If ground-truth bounding boxes are provided, compute IoU and mAP.
    """
    global experiment_metrics, map_data
    
    # Normalize inputs
    gt = None if ground_truth_label is None else str(ground_truth_label)
    has_gt_object = gt is not None and gt.lower() not in ["empty", "unknown"]
    
    predictions = scores_list if isinstance(scores_list, list) else []
    num_predictions = len(predictions)
    predicted_labels = [str(p.get("label")) for p in predictions if p and p.get("label") is not None]
    
    # Detection mode vs classification mode
    detection_mode = isinstance(ground_truth_boxes, list) and len(ground_truth_boxes) > 0
    increment_true_positive = 0
    increment_false_negative = 0
    increment_false_positive = 0
    
    if detection_mode:
        gt_boxes = [g for g in ground_truth_boxes if g and g.get("bounding_box") is not None]
        experiment_metrics["gt_boxes_count"] += len(gt_boxes)
        _update_map_structures(predictions, gt_boxes)
        matches, used_preds, used_gts = _greedy_match(predictions, gt_boxes, 0.5)
        tp_count = 0
        sum_iou_img = 0.0
        for pi, gi, iou in matches:
            if str(predictions[pi].get("label")) == str(gt_boxes[gi].get("label")):
                tp_count += 1
                sum_iou_img += iou
        fp_count = max(num_predictions - len(used_preds), 0)
        fn_count = max(len(gt_boxes) - len(used_gts), 0)
        increment_true_positive = tp_count
        increment_false_positive = fp_count
        increment_false_negative = fn_count
        if tp_count > 0:
            experiment_metrics["sum_iou"] += sum_iou_img
            experiment_metrics["num_iou_pairs"] += tp_count
    else:
        has_correct_prediction = has_gt_object and any(lbl == gt for lbl in predicted_labels)
        increment_true_positive = 1 if has_correct_prediction else 0
        increment_false_negative = 1 if has_gt_object and not has_correct_prediction else 0
        increment_false_positive = max(num_predictions - (1 if has_correct_prediction else 0), 0)
    
    # Update totals
    experiment_metrics["total_images"] += 1
    experiment_metrics["total_predictions"] += num_predictions
    if detection_mode:
        experiment_metrics["total_ground_truth_objects"] += len(ground_truth_boxes)
    else:
        experiment_metrics["total_ground_truth_objects"] += 1 if has_gt_object else 0
    experiment_metrics["true_positives"] += increment_true_positive
    experiment_metrics["false_negatives"] += increment_false_negative
    experiment_metrics["false_positives"] += increment_false_positive
    
    # Derived metrics
    tp = float(experiment_metrics["true_positives"])
    fp = float(experiment_metrics["false_positives"])
    fn = float(experiment_metrics["false_negatives"])
    precision = (tp / (tp + fp)) if (tp + fp) > 0 else 0.0
    recall = (tp / (tp + fn)) if (tp + fn) > 0 else 0.0
    f1 = (2.0 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    experiment_metrics["precision"] = precision
    experiment_metrics["recall"] = recall
    experiment_metrics["f1_score"] = f1
    
    # Mean IoU
    if experiment_metrics["num_iou_pairs"] > 0:
        experiment_metrics["mean_iou"] = experiment_metrics["sum_iou"] / experiment_metrics["num_iou_pairs"]
    
    # mAP
    if experiment_metrics["gt_boxes_count"] > 0:
        ap50 = _compute_ap(map_data[0.5], experiment_metrics["gt_boxes_count"]) if 0.5 in map_data else 0.0
        ap_values = [_compute_ap(map_data[t], experiment_metrics["gt_boxes_count"]) for t in map_thresholds]
        map_50_95 = sum(ap_values) / len(ap_values) if ap_values else 0.0
        experiment_metrics["map_50"] = ap50
        experiment_metrics["map_50_95"] = map_50_95


# ============================================================================
# Kafka streaming
# ============================================================================
def build_event_payload(uuid):
    """
    Build event payload from in-memory entry for Kafka streaming.
    
    Event structure matches publish_test_event.py SAMPLE_EVENT for Neo4j Kafka Connector:
    - Identity fields first (device_id, experiment_id, user_id, model_id)
    - Image metadata (image_count, UUID, image_name, ground_truth)
    - Timestamps (image_receiving_timestamp, image_scoring_timestamp, image_store_delete_time)
    - Prediction result (label, probability, image_decision)
    - Flattened scores
    - Running experiment metrics
    """
    global existing_image_mapping, experiment_metrics
    
    entry = existing_image_mapping.get(uuid)
    if not entry:
        return None
    
    # Extract fields
    image_count = entry.get("image_count")
    image_name = entry.get("image_name")
    ground_truth = entry.get("ground_truth")
    image_receiving_timestamp = entry.get("image_receiving_timestamp")
    image_scoring_timestamp = entry.get("image_scoring_timestamp")
    image_store_delete_time = entry.get("image_store_delete_time") or entry.get("image_delete_time")
    image_decision = entry.get("image_decision")
    model_id = entry.get("model_id") or MODEL_ID
    
    # Extract scores
    scores = entry.get("score", [])
    flattened_scores = json.dumps(scores) if scores else None
    
    # Extract highest probability label
    label = None
    probability = 0.0
    if scores:
        highest_score = max(scores, key=lambda x: x.get("probability", 0.0))
        label = highest_score.get("label")
        probability = highest_score.get("probability", 0.0)
    
    # Build event payload - SAME STRUCTURE AS publish_test_event.py SAMPLE_EVENT
    event = {
        # Identity fields
        "domain": CKN_DOMAIN,
        "device_id": DEVICE_ID,
        "experiment_id": EXPERIMENT_ID,
        "user_id": USER_ID,
        "model_id": model_id,
        # Image metadata
        "image_count": image_count,
        "UUID": uuid,
        "image_name": image_name,
        "ground_truth": ground_truth,
        # Timestamps
        "image_receiving_timestamp": image_receiving_timestamp,
        "image_scoring_timestamp": image_scoring_timestamp,
        "image_store_delete_time": image_store_delete_time,
        # Prediction result (highest probability label)
        "label": label,
        "probability": probability,
        "image_decision": image_decision,
        # Flattened scores as JSON string
        "flattened_scores": flattened_scores,
        # Running experiment metrics
        "total_images": experiment_metrics["total_images"],
        "total_predictions": experiment_metrics["total_predictions"],
        "total_ground_truth_objects": experiment_metrics["total_ground_truth_objects"],
        "true_positives": experiment_metrics["true_positives"],
        "false_positives": experiment_metrics["false_positives"],
        "false_negatives": experiment_metrics["false_negatives"],
        "precision": experiment_metrics["precision"],
        "recall": experiment_metrics["recall"],
        "f1_score": experiment_metrics["f1_score"],
        "mean_iou": experiment_metrics["mean_iou"],
        "map_50": experiment_metrics["map_50"],
        "map_50_95": experiment_metrics["map_50_95"],
    }
    
    return event


def stream_event_to_kafka(uuid):
    """Stream event to Kafka broker."""
    global kafka_producer, processed_uuids
    
    if not kafka_producer:
        logger.debug(f"Kafka producer not initialized, skipping stream for UUID: {uuid}")
        return
    
    if uuid in processed_uuids:
        logger.debug(f"UUID {uuid} already processed, skipping")
        return
    
    event_data = build_event_payload(uuid)
    if not event_data:
        logger.warning(f"Could not build event payload for UUID: {uuid}")
        return
    
    try:
        # Event already includes device_id, experiment_id, user_id from build_event_payload
        row_json = json.dumps(event_data, indent=2)
        
        # Log the event before publishing
        logger.info("="*60)
        logger.info(f"KAFKA EVENT - Publishing to topic '{KAFKA_TOPIC}'")
        logger.info("="*60)
        logger.info(f"Key: {EXPERIMENT_ID}")
        logger.info(f"Event payload:")
        logger.info(row_json)
        logger.info("="*60)
        
        # Produce to Kafka wrapped in a Connect schema envelope (use non-indented JSON for actual message)
        envelope = build_connect_envelope(event_data, EVENT_FIELD_TYPES, EVENT_REQUIRED_FIELDS)
        kafka_producer.produce(KAFKA_TOPIC, key=EXPERIMENT_ID, value=json.dumps(envelope))
        kafka_producer.flush()
        
        processed_uuids.add(uuid)
        logger.info(f"Successfully streamed event to Kafka for UUID: {uuid}")
        
    except Exception as e:
        logger.error(f"Error streaming to Kafka: {e}")


# ============================================================================
# Power summary processing
# ============================================================================
def process_power_summary():
    """Read power summary file and stream to Kafka."""
    global kafka_producer
    
    if ENABLE_POWER_MONITORING != 'true':
        logger.info("Power monitoring not enabled, skipping power summary.")
        return
    
    if not kafka_producer:
        logger.info("Kafka producer not available, skipping power summary streaming.")
        return
    
    if not POWER_SUMMARY_FILE:
        logger.info("Power summary file not configured, skipping.")
        return
    
    logger.info(f"Waiting for power summary file: {POWER_SUMMARY_FILE}")
    
    attempt = 0
    while attempt < POWER_SUMMARY_MAX_TRIES:
        if os.path.exists(POWER_SUMMARY_FILE):
            try:
                with open(POWER_SUMMARY_FILE, 'r') as f:
                    data = json.load(f)
                
                power_summary = data.get("plugin power summary report", [])
                
                # Build flattened event - SAME STRUCTURE AS publish_test_event.py POWER_SUMMARY_EVENT
                # experiment_id first, then per-plugin fields, then totals
                flattened_event = {
                    "experiment_id": EXPERIMENT_ID,
                }
                
                total_cpu = 0.0
                total_gpu = 0.0
                
                for plugin_data in power_summary:
                    plugin_name = plugin_data.get("plugin", "unknown")
                    cpu = plugin_data.get("cpu_power_consumption", 0.0)
                    gpu = plugin_data.get("gpu_power_consumption", 0.0)
                    
                    flattened_event[f"{plugin_name}_cpu_power_consumption"] = cpu
                    flattened_event[f"{plugin_name}_gpu_power_consumption"] = gpu
                    total_cpu += cpu
                    total_gpu += gpu
                
                flattened_event["total_cpu_power_consumption"] = total_cpu
                flattened_event["total_gpu_power_consumption"] = total_gpu
                
                # Log the event before publishing
                power_json = json.dumps(flattened_event, indent=2)
                logger.info("="*60)
                logger.info(f"KAFKA POWER EVENT - Publishing to topic '{POWER_SUMMARY_TOPIC}'")
                logger.info("="*60)
                logger.info(f"Key: {EXPERIMENT_ID}")
                logger.info(f"Power summary payload:")
                logger.info(power_json)
                logger.info("="*60)
                
                # Stream to Kafka wrapped in a Connect schema envelope
                power_envelope = build_connect_envelope(
                    flattened_event, build_power_field_types(flattened_event), {"experiment_id"}
                )
                kafka_producer.produce(POWER_SUMMARY_TOPIC, key=EXPERIMENT_ID, value=json.dumps(power_envelope))
                kafka_producer.flush()
                
                logger.info("Power summary successfully streamed to Kafka.")
                return
                
            except Exception as e:
                logger.error(f"Error processing power summary: {e}")
                return
        
        attempt += 1
        logger.info(f"Power summary file not found, attempt {attempt}/{POWER_SUMMARY_MAX_TRIES}")
        time.sleep(POWER_SUMMARY_TIMEOUT)
    
    logger.warning("Power summary file not found after all attempts.")


# ============================================================================
# In-memory state management (replaces file-based image_mapping_final.json)
# ============================================================================
def get_socket():
    context = zmq.Context()
    return get_plugin_socket(context, PORT)


def compute_total_images_generated():
    """Reads uuid_image_mapping file to determine how many images were generated."""
    try:
        with open(uuid_image_mapping_path, 'r') as f:
            d = json.load(f)
        return len(d.keys())
    except Exception as e:
        logger.error(f"Error reading uuid_image_mapping: {e}")
        return -1


def compute_total_images_processed():
    """Count images in memory with image_decision set."""
    global existing_image_mapping
    total = 0
    for _, v in existing_image_mapping.items():
        if v.get("image_decision"):
            total += 1
    return total


def update_mapping(uuid, updated_data):
    """
    Update the in-memory mapping for a given image UUID.
    If UUID is new, fetch base info from uuid_image_mapping.json.
    """
    global existing_image_mapping, uuids_with_errors
    
    # If UUID not yet in mapping, fetch from uuid_image_mapping.json
    if uuid not in existing_image_mapping:
        logger.debug(f"Fetching {uuid} from {uuid_image_mapping_path}")
        uuid_image_mapping = {}
        try:
            with open(uuid_image_mapping_path, 'r') as f:
                uuid_image_mapping = json.load(f)
                # Try to recover any previously failed UUIDs
                for failed_uuid in list(uuids_with_errors):
                    if failed_uuid in uuid_image_mapping:
                        if failed_uuid in existing_image_mapping:
                            existing_image_mapping[failed_uuid].update(uuid_image_mapping[failed_uuid])
                        else:
                            existing_image_mapping[failed_uuid] = uuid_image_mapping[failed_uuid]
                        uuids_with_errors.remove(failed_uuid)
        except json.JSONDecodeError as e:
            logger.error(f"JSON decode error reading uuid_image_mapping for {uuid}: {e}")
            uuids_with_errors.append(uuid)
        except FileNotFoundError:
            logger.error(f"uuid_image_mapping file not found: {uuid_image_mapping_path}")
        
        # Get base info or create minimal entry
        existing_image_mapping[uuid] = uuid_image_mapping.get(uuid, {"UUID": uuid})
    
    # Update with new data
    for key, value in updated_data.items():
        existing_image_mapping[uuid][key] = value
    
    # If this update set image_decision, update metrics and stream to Kafka
    if "image_decision" in updated_data:
        entry = existing_image_mapping[uuid]
        ground_truth = entry.get("ground_truth")
        scores = entry.get("score", [])
        ground_truth_boxes = entry.get("ground_truth_boxes") or entry.get("ground_truth_bboxes")
        
        # Update experiment metrics
        _update_experiment_metrics(ground_truth, scores, ground_truth_boxes)
        
        # Stream to Kafka
        stream_event_to_kafka(uuid)


# ============================================================================
# Main event loop
# ============================================================================
def main():
    """
    Main loop for CKN plugin.
    Waits for new messages on ZMQ and processes accordingly:
    1. ImageReceived/ImageScored/ImageStored/ImageDeleted: update in-memory mapping
    2. PluginTerminating: compute total images, trigger shutdown when done
    """
    global received_terminating_signal, total_images_generated, total_images_processed
    
    # Initialize Kafka if configured
    init_kafka_producer()
    
    done = False
    while not done:
        socket = get_socket()
        try:
            message = get_next_msg(socket)
        except zmq.error.Again:
            logger.debug(f"Got zmq.error.Again; waited {SOCKET_TIMEOUT} ms without message")
            continue
        except Exception as e:
            logger.debug(f"Got exception from get_next_msg: {type(e)}: {e}")
            done = True
            logger.info("CKN plugin stopping due to timeout limit...")
            continue
        
        if not message:
            logger.info("No message found in get_next_msg")
            continue
        
        logger.info("Got a message from the event socket")
        event = socket_message_to_typed_event(message)
        
        if isinstance(event, ImageReceivedEvent):
            uuid = event.ImageUuid().decode('utf-8')
            timestamp = event.EventCreateTs().decode('utf-8').strip("'")
            logger.info(f"Image received {uuid} {timestamp}")
            update_mapping(uuid, {"image_receiving_timestamp": timestamp})
        
        elif isinstance(event, ImageScoredEvent):
            uuid = event.ImageUuid().decode('utf-8')
            scores = []
            for i in range(event.ScoresLength()):
                label = event.Scores(i).Label().decode('utf-8')
                prob = event.Scores(i).Probability()
                scores.append({"label": label, "probability": prob})
                bbox = event.Scores(i).Bbox()
                if bbox:
                    bbox_list = [bbox.XCenter(), bbox.YCenter(), bbox.Width(), bbox.Height()]
                    scores.append({"label": label, "probability": prob, "bounding_box": bbox_list})
                else:
                    scores.append({"label": label, "probability": prob})
            timestamp = event.EventCreateTs().decode('utf-8')
            logger.info(f"Image scored {uuid} {scores} {timestamp}")
            update_mapping(uuid, {"image_scoring_timestamp": timestamp, "score": scores})
        
        elif isinstance(event, ImageStoredEvent):
            uuid = event.ImageUuid().decode('utf-8')
            timestamp = event.EventCreateTs().decode('utf-8')
            destination = event.Destination().decode('utf-8')
            logger.info(f"Image stored {uuid} {timestamp} {destination}")
            update_mapping(uuid, {"image_store_delete_time": timestamp, "image_decision": destination})
        
        elif isinstance(event, ImageDeletedEvent):
            uuid = event.ImageUuid().decode('utf-8')
            timestamp = event.EventCreateTs().decode('utf-8')
            logger.info(f"Image deleted {uuid} {timestamp}")
            update_mapping(uuid, {"image_delete_time": timestamp, "image_decision": "Deleted"})
        
        elif isinstance(event, PluginTerminatingEvent):
            plugin_name = event.PluginName().decode('utf-8')
            if plugin_name == 'ext_image_gen_plugin':
                logger.info("Received Terminating signal from image generating plugin")
                received_terminating_signal = True
                total_images_generated = compute_total_images_generated()
                logger.info(f"Total images generated: {total_images_generated}")
        
        # Check if all images processed
        if received_terminating_signal:
            total_images_processed = compute_total_images_processed()
            logger.info(f"CKN plugin has processed: {total_images_processed} out of {total_images_generated}")
            
            if total_images_generated < 0:
                total_images_generated = compute_total_images_generated()
        
        # Shutdown when all images processed
        if (received_terminating_signal 
            and total_images_generated > 0 
            and total_images_generated == total_images_processed):
            logger.info("All images processed. Initiating shutdown...")

            # Send PluginTerminate first: the power monitor plugin only writes
            # power_summary_report.json when it receives this event, so it must
            # be told to stop before we wait on the summary file.
            send_terminate_plugin_fb_event(socket, "*", EXPERIMENT_END_SIGNAL)
            logger.info("Sent PluginTerminate * event")

            # Now wait for the power summary file and stream it to Kafka
            process_power_summary()

            time.sleep(1)
            send_quit_command(socket)
            logger.info("Sent quit command.")
            sys.exit()
        else:
            logger.debug(f"Event: {event}")


if __name__ == '__main__':
    logger.info("CKN plugin starting...")
    main()
    logger.info("CKN plugin exiting...")
