name: Test Suite

on:
  release:
    types: [released]
  push:
    branches:
      - dev
      - trigger_tests

jobs:
  Test_Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Test Suite github action
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TESTSUITE_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ICICLE-ai/ml_workbench_test_suite/dispatches \
            -d '{"event_type":"dispatch-event"}'
